# This is just a sample config file
# See the readme for proper setup
# DO NOT UPLOAD REAL VALUES TO THE REPO!
browser:
  driver: chrome
  maximized: True
  implicit_wait: 10  # in seconds
app:
  base_url: http://example.com
  port: 80
test:
  max-runtime: 300
  output_dir: output
  html_report_filename: pytest_report.html
  append_date_to_files: True
  debug: True  # breakpoint on test exception that leaves the browser running at point of failure

